- name: Lops
  hosts: all
  become: yes

  vars:
    file_src: play.yml
    file_dest: /home/dir1

  tasks:
  - name: Create Folder
    file:
      path: "/home/{{item}}"
      state: directory
    loop:
      - dir1
      - dir2

  - name: Copy File
    copy:
      src: "{{file_src}}"
      dest: "{{file_dest}}"
      mode: 0777 

  - name: Install package
    apt:
      pkg: tree
      state: present
